version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.lambda
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - .db_data/db.sqlite3:/db.sqlite3
      - static_volume:/usr/src/app/jobs/staticfiles
    ports:
      - "8000:8000"

volumes:
  static_volume:
